# Model Development 

## Logistic regression

In [20]:
from taxipred.utils.constants import TAXI_REMOVED_NA
import pandas as pd 
df = pd.read_csv(TAXI_REMOVED_NA)

df.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4             41.79                3       4.60         1.77             0.11   

   Trip_Duration_Minutes  Trip_Price  Time_of_Day_Afternoon  \
0                  53.82     36.2624                      0   
1                  37.27     52.9032                      0   
2                 116.81     36.4698                      0   
3                  89.33     60.2028                      1   
4                  86.95     88.1328                      0   

   Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
0                    0                    1                  0   
1                    1                    0                  0   
2                    1                    0                  0   
3                    0                    0                  0   
4                    0                    0                  1   

   Day_of_Week_Weekday  Day_of_Week_Weekend  
0                    1                    0  
1                    0                    1  
2                    1                    0  
3                    0                    1  
4                    0                    1

In [21]:
y=df["Trip_Price"]
y.head()

0    36.2624
1    52.9032
2    36.4698
3    60.2028
4    88.1328
Name: Trip_Price, dtype: float64

In [22]:
X = df.drop("Trip_Price", axis=1)
X.head()

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4             41.79                3       4.60         1.77             0.11   

   Trip_Duration_Minutes  Time_of_Day_Afternoon  Time_of_Day_Evening  \
0                  53.82                      0                    0   
1                  37.27                      0                    1   
2                 116.81                      0                    1   
3                  89.33                      1                    0   
4                  86.95                      0                    0   

   Time_of_Day_Morning  Time_of_Day_Night  Day_of_Week_Weekday  \
0                    1                  0                    1   
1                    0                  0                    0   
2                    0                  0                    1   
3                    0                  0                    0   
4                    0                  1                    0   

   Day_of_Week_Weekend  
0                    0  
1                    1  
2                    0  
3                    1  
4                    1

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

print(f"{X_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_train.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (456, 12)
X_test.shape = (225, 12)
y_train.shape = (456,)
y_test.shape = (225,)


In [24]:
X_train.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  \
50              38.79                2       3.95         1.88   
583             24.13                1       3.37         1.92   
220             42.92                3       4.66         1.05   
166             19.87                1       4.40         1.34   
206             41.96                4       2.21         1.22   

     Per_Minute_Rate  Trip_Duration_Minutes  Time_of_Day_Afternoon  \
50              0.33                  82.93                      1   
583             0.31                  23.71                      1   
220             0.34                  62.85                      0   
166             0.38                  27.60                      1   
206             0.19                  80.28                      1   

     Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
50                     0                    0                  0   
583                    0                    0                  0   
220                    0                    1                  0   
166                    0                    0                  0   
206                    0                    0                  0   

     Day_of_Week_Weekday  Day_of_Week_Weekend  
50                     1                    0  
583                    1                    0  
220                    1                    0  
166                    0                    1  
206                    0                    1

In [25]:
y_train.head()

50     104.2421
583     57.0497
220     71.0950
166     41.5138
206     68.6544
Name: Trip_Price, dtype: float64

In [26]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
scale.fit(X_train)
scaled_X_train = scale.transform(X_train)
scaled_X_test = scale.transform(X_test)

scaled_X_test.shape, scaled_X_train.shape

((225, 12), (456, 12))

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(scaled_X_train,y_train)
model.coef_, model.intercept_

(array([17.24119925,  0.26363852,  0.80812695,  9.91139922,  6.99747567,
         9.01141551,  0.74996096,  0.45185149,  1.28022299,  0.18067697,
        -0.14087748,  0.24071933]),
 np.float64(51.58155087719298))

In [28]:
test_sample_1 = scaled_X_test[0].reshape(1,-1)
test_sample_2 = y_test.values[0]
test_sample_1, test_sample_2

(array([[ 0.04224297, -0.46813859, -1.1786586 , -0.86088091, -0.65018035,
          1.57416358, -0.74942901,  1.98910074, -0.62130366, -0.34299717,
          0.75658033, -0.68281618]]),
 np.float64(48.4142))

In [29]:
pred_y = model.predict(scaled_X_test)
pred_y

array([ 51.54563623,  75.51489813,  45.1503705 ,  33.70369133,
        53.07960191,  55.63080739,  82.9949429 ,  45.40144168,
        59.00081089,  25.67106867,  -0.35383714,  64.84141239,
        63.86179578,  19.92110176,  23.27723097,  64.54541785,
        61.48877961,  73.89497814,  45.91761931,  64.8980399 ,
        53.19030432,  73.87430419,  84.41566793,  39.38027491,
        40.16524793,  44.61216531,  84.88841954,  62.1695736 ,
        42.70933045,  87.4744498 ,  89.71172593,  23.30330499,
        16.8807531 ,  22.87812785,  79.6616771 ,  60.69482129,
        52.85733989,  49.86148747,  68.50292175,  70.00417191,
        15.22858544,  44.94792964,  87.5062968 ,  59.86147002,
         3.90519576,  32.25257687,  31.58677465,  70.50293317,
        50.19270619,  19.26470498,  33.99632798,  73.05340356,
        82.23141277,  73.2508307 ,  48.30907252,  30.99416699,
        60.5759023 ,  25.43659618,  63.11266846,  50.29595701,
        -0.43328099,  39.03111412,  69.83268264,  69.55

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mean_ab_er = mean_absolute_error(y_test,pred_y)
mean_sq_er = mean_squared_error(y_test,pred_y)
root_me_sq_er = np.sqrt(mean_sq_er)

print(f"Mean absolut error {mean_ab_er}, Mean squarerd error {mean_sq_er}, Root Mean squared error {root_me_sq_er}")

Mean absolut error 5.396264816169342, Mean squarerd error 46.9322216032423, Root Mean squared error 6.850709569325085


comparing with baseline (got from LLM)

In [34]:
base_line = np.mean(y_test)
base_with_mae = mean_absolute_error(y_test, [base_line]*len(y_test))
base_line, base_with_mae

(np.float64(51.76569466666667), 19.48548848592593)