# Model Development 

## Logistic regression

In [2]:
from taxipred.utils.constants import TAXI_REMOVED_NA
import pandas as pd 
df = pd.read_csv(TAXI_REMOVED_NA)

df.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4             41.79                3       4.60         1.77             0.11   

   Trip_Duration_Minutes  Trip_Price  Time_of_Day_Afternoon  \
0                  53.82     36.2624                      0   
1                  37.27     52.9032                      0   
2                 116.81     36.4698                      0   
3                  89.33     60.2028                      1   
4                  86.95     88.1328                      0   

   Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
0                    0                    1                  0   
1                    1                    0                  0   
2                    1                    0                  0   
3                    0                    0                  0   
4                    0                    0                  1   

   Day_of_Week_Weekday  Day_of_Week_Weekend  
0                    1                    0  
1                    0                    1  
2                    1                    0  
3                    0                    1  
4                    0                    1

In [3]:
y=df["Trip_Price"]
y.head()

0    36.2624
1    52.9032
2    36.4698
3    60.2028
4    88.1328
Name: Trip_Price, dtype: float64

In [4]:
X = df.drop("Trip_Price", axis=1)
X.head()

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4             41.79                3       4.60         1.77             0.11   

   Trip_Duration_Minutes  Time_of_Day_Afternoon  Time_of_Day_Evening  \
0                  53.82                      0                    0   
1                  37.27                      0                    1   
2                 116.81                      0                    1   
3                  89.33                      1                    0   
4                  86.95                      0                    0   

   Time_of_Day_Morning  Time_of_Day_Night  Day_of_Week_Weekday  \
0                    1                  0                    1   
1                    0                  0                    0   
2                    0                  0                    1   
3                    0                  0                    0   
4                    0                  1                    0   

   Day_of_Week_Weekend  
0                    0  
1                    1  
2                    0  
3                    1  
4                    1

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

print(f"{X_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_train.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (421, 12)
X_test.shape = (208, 12)
y_train.shape = (421,)
y_test.shape = (208,)


In [6]:
X_train.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  \
146             45.83                4       4.50         1.36   
550             33.29                3       4.48         1.10   
405             37.53                4       2.19         1.84   
123              5.97                4       4.69         1.89   
222             47.13                4       4.15         1.30   

     Per_Minute_Rate  Trip_Duration_Minutes  Time_of_Day_Afternoon  \
146             0.39                  54.66                      0   
550             0.19                  52.09                      1   
405             0.48                  62.05                      1   
123             0.32                  90.57                      1   
222             0.23                   6.47                      0   

     Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
146                    1                    0                  0   
550                    0                    0                  0   
405                    0                    0                  0   
123                    0                    0                  0   
222                    1                    0                  0   

     Day_of_Week_Weekday  Day_of_Week_Weekend  
146                    1                    0  
550                    1                    0  
405                    1                    0  
123                    1                    0  
222                    1                    0

In [7]:
y_train.head()

146     88.1462
550     50.9961
405    101.0292
123     44.9557
222     66.9071
Name: Trip_Price, dtype: float64

In [8]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
scale.fit(X_train)
scaled_X_train = scale.transform(X_train)
scaled_X_test = scale.transform(X_test)

scaled_X_test.shape, scaled_X_train.shape

((208, 12), (421, 12))

In [19]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(scaled_X_train,y_train)
model.coef_, model.intercept_

(array([ 3.60899958e+01, -2.39776332e-02,  1.13136677e+00,  1.03088425e+01,
         6.60866988e+00,  9.81126036e+00,  1.24760497e-01, -2.80039999e-01,
         6.27184488e-01, -7.15798942e-01, -2.99436164e-01,  2.99436164e-01]),
 np.float64(56.3768369816603))

In [22]:
test_sample_1 = scaled_X_test[0].reshape(1,-1)
test_sample_2 = y_test.values[0]
test_sample_1, test_sample_2

(array([[-0.02601053, -1.37401063, -0.89786848,  0.29947622, -0.868739  ,
         -0.26871171, -0.80282704, -0.53982501,  1.6312172 , -0.35023801,
         -1.47153441,  1.47153441]]),
 np.float64(47.8069))

In [24]:
pred_y = model.predict(scaled_X_test)
pred_y

array([ 5.13709342e+01,  7.33148705e+01,  7.87855700e+01,  7.98861426e+01,
        1.06450535e+02,  2.35595202e+01,  2.10577781e+01,  3.49401979e+01,
        9.89215226e+01,  1.06167256e+02,  5.10874777e+01, -3.68654059e-01,
        3.59712610e+01,  4.57989980e+01, -5.49173529e+00,  2.76924812e+02,
        4.87990097e+01,  4.42162428e+01,  3.78991572e+01,  1.01831400e+02,
        1.04470652e+02,  8.34309963e+01,  6.41500878e+01,  9.87681413e+01,
        4.81782546e+01,  3.36819044e+01,  3.70374167e+01,  6.06744397e+01,
        9.36525870e+01,  5.83169837e+01,  7.48064267e+01,  6.89618893e+00,
        6.26770425e+01,  6.64350747e+01,  3.82236081e+01,  7.05412402e+01,
        3.32159514e+01,  4.38250276e+01,  7.40024663e+01,  4.50861578e+01,
        1.07657397e+02,  3.63344607e+01,  7.62241119e+01,  8.86162926e+01,
        5.67366887e+01,  9.76653649e+01,  7.64498662e+01,  2.34976688e+01,
        7.30065092e+01,  7.62663481e+01,  6.57955369e+01,  3.29181538e+01,
        2.74350054e+02, -

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mean_ab_er = mean_absolute_error(y_test,pred_y)
mean_sq_er = mean_squared_error(y_test,pred_y)
root_me_sq_er = np.sqrt(mean_sq_er)

print(f"Mean absolut error {mean_ab_er}, Mean squarerd error {mean_sq_er}, Root Mean squared error {root_me_sq_er}")

Mean absolut error 8.155224811572584, Mean squarerd error 153.72533488136466, Root Mean squared error 12.398602134166765
