# Model Development 

## Logistic regression

In [35]:
from taxipred.utils.constants import TAXI_REMOVED_NA
import pandas as pd 
df = pd.read_csv(TAXI_REMOVED_NA)

df.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4              9.91                2       2.32         1.26             0.34   

   Trip_Duration_Minutes  Trip_Price  Time_of_Day_Afternoon  \
0                  53.82     36.2624                      0   
1                  37.27     52.9032                      0   
2                 116.81     36.4698                      0   
3                  89.33     60.2028                      1   
4                  41.72     28.9914                      0   

   Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
0                    0                    1                  0   
1                    1                    0                  0   
2                    1                    0                  0   
3                    0                    0                  0   
4                    1                    0                  0   

   Day_of_Week_Weekday  Day_of_Week_Weekend  
0                    1                    0  
1                    0                    1  
2                    1                    0  
3                    0                    1  
4                    1                    0

In [36]:
y=df["Trip_Price"]
y.head()

0    36.2624
1    52.9032
2    36.4698
3    60.2028
4    28.9914
Name: Trip_Price, dtype: float64

In [37]:
X = df.drop("Trip_Price", axis=1)
X.head()

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0             19.35                3       3.56         0.80             0.32   
1             36.87                1       2.70         1.21             0.15   
2             30.33                4       3.48         0.51             0.15   
3              8.64                2       2.55         1.71             0.48   
4              9.91                2       2.32         1.26             0.34   

   Trip_Duration_Minutes  Time_of_Day_Afternoon  Time_of_Day_Evening  \
0                  53.82                      0                    0   
1                  37.27                      0                    1   
2                 116.81                      0                    1   
3                  89.33                      1                    0   
4                  41.72                      0                    1   

   Time_of_Day_Morning  Time_of_Day_Night  Day_of_Week_Weekday  \
0                    1                  0                    1   
1                    0                  0                    0   
2                    0                  0                    1   
3                    0                  0                    0   
4                    0                  0                    1   

   Day_of_Week_Weekend  
0                    0  
1                    1  
2                    0  
3                    1  
4                    0

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

print(f"{X_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_train.shape = }")
print(f"{y_test.shape = }")

X_train.shape = (377, 12)
X_test.shape = (187, 12)
y_train.shape = (377,)
y_test.shape = (187,)


In [39]:
X_train.head(5)

Trip_Distance_km  Passenger_Count  Base_Fare  Per_Km_Rate  \
212             19.23                3       3.48         1.90   
253             49.66                4       4.86         1.15   
328             17.94                1       3.69         0.69   
301             26.50                1       4.44         0.81   
262             14.77                4       4.80         1.21   

     Per_Minute_Rate  Trip_Duration_Minutes  Time_of_Day_Afternoon  \
212             0.42                 117.75                      0   
253             0.16                  68.75                      1   
328             0.49                  85.75                      0   
301             0.45                 114.61                      0   
262             0.28                 113.40                      1   

     Time_of_Day_Evening  Time_of_Day_Morning  Time_of_Day_Night  \
212                    0                    1                  0   
253                    0                    0                  0   
328                    0                    1                  0   
301                    0                    1                  0   
262                    0                    0                  0   

     Day_of_Week_Weekday  Day_of_Week_Weekend  
212                    1                    0  
253                    0                    1  
328                    1                    0  
301                    1                    0  
262                    0                    1

In [40]:
y_train.head()

212    89.4720
253    72.9690
328    58.0861
301    77.4795
262    54.4237
Name: Trip_Price, dtype: float64

In [41]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
scale.fit(X_train)
scaled_X_train = scale.transform(X_train)
scaled_X_test = scale.transform(X_test)

scaled_X_test.shape, scaled_X_train.shape

((187, 12), (377, 12))

In [42]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(scaled_X_train,y_train)
model.coef_, model.intercept_

(array([35.45910474, -0.12818304, -0.66228012, 10.6613922 ,  7.35505793,
         8.80263676, -0.14950703, -0.54590128,  0.64897442,  0.        ,
        -0.11057291,  0.11057291]),
 np.float64(57.4762916431788))

In [43]:
test_sample_1 = scaled_X_test[0].reshape(1,-1)
test_sample_2 = y_test.values[0]
test_sample_1, test_sample_2

(array([[-0.07210895, -0.44750603, -0.52372197,  0.87748376,  0.87051182,
         -0.28337392, -0.89176123,  1.82574186, -0.69588215,  0.        ,
          0.65837685, -0.65837685]]),
 np.float64(65.9299))

In [44]:
pred_y = model.predict(scaled_X_test)
pred_y

array([ 6.71264549e+01,  7.73327134e+01,  3.28953111e+01,  3.71112707e+01,
        3.57104926e+01,  3.89671602e+01,  1.11694858e+01,  1.52852206e+01,
        4.91942250e+01,  5.09516322e+01,  5.81919251e+01,  5.16797583e+01,
        7.19968310e+01,  4.06958694e+01,  6.02517445e+01,  2.03606306e+02,
        4.78258593e+01,  3.98239779e+01,  2.37408696e+01,  6.25175138e+01,
        8.71473687e+01,  6.51889247e+01,  5.57507750e+01,  4.17827507e+01,
       -1.76530975e+01,  2.17427270e+01,  9.51996418e+01,  5.87114046e+01,
        1.04537538e+02,  7.40869265e+01,  7.19746525e+01,  1.59021241e+01,
       -3.26912715e+00,  2.45645612e+01,  6.11135747e+01,  7.79139688e+01,
        3.71905638e+01,  1.07056436e+02,  8.11395024e+01,  1.52570149e+01,
        8.77349744e+01,  2.84995386e+01,  7.49950330e+01,  7.29881149e+01,
        4.58304835e+01,  4.80538250e+01,  8.25896303e+01,  7.76867444e+01,
        1.09589356e+01,  7.56492359e+00,  2.10401175e+01,  8.31629030e+01,
        4.81123661e+01,  

In [45]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mean_ab_er = mean_absolute_error(y_test,pred_y)
mean_sq_er = mean_squared_error(y_test,pred_y)
root_me_sq_er = np.sqrt(mean_sq_er)

print(f"Mean absolut error {mean_ab_er}, Mean squarerd error {mean_sq_er}, Root Mean squared error {root_me_sq_er}")

Mean absolut error 9.501317345842137, Mean squarerd error 271.639742629564, Root Mean squared error 16.481496977810117


comparing with baseline (got from LLM)

In [46]:
base_line = np.mean(y_test)
base_with_mae = mean_absolute_error(y_test, [base_line]*len(y_test))
base_line, base_with_mae

(np.float64(57.1563652603273), 25.763832419671406)